language: python
python:
  - "2.7"
script: pytest --cov=spatial_efd/
branches:
  only:
    - master
install:
 - pip install .
 - pip install -r .travis.requirements.txt
after_success:
 - codecov
 - flake8 spatial_efd/spatial_efd.py
 - flake8 tests/test_efd.py
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
