dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions - Failing on Travis as of 10/8/2020
  # - "pypy3"

services:
  - xvfb
script: pytest
branches:
  only:
    - master
install:
 - pip install .
 - pip install -r .requirements.txt
after_success:
 - pytest --cov=spatial_efd/
 - codecov
 - flake8 spatial_efd/spatial_efd.py
 - flake8 tests/test_efd.py
