dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3.5"

script: pytest
branches:
  only:
    - master
install:
 - pip install .
 - pip install -r .requirements.txt
after_success:
 - pytest --cov=spatial_efd/
 - codecov
 - flake8 spatial_efd/spatial_efd.py
 - flake8 tests/test_efd.py
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
