image: Visual Studio 2019

environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- "pip install -r .requirements.txt"

test_script:
- "%PYTHON%\\python.exe -m pytest"
