version: 1.0.{build}
image: Visual Studio 2019
init:
- cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
environment:
  matrix:
  - PYTHON: C:\\Python37-x64
  - PYTHON: C:\\Python37
  - PYTHON: C:\\Python38-x64
  - PYTHON: C:\\Python38
install:
- cmd: '%PYTHON%\\python.exe -m pip install -r .requirements.txt'
test_script:
- cmd: '%PYTHON%\\python.exe -m pytest'
