version: 1.0.{build}
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build_script:
- ps: pip install -r .requirements.txt
test_script:
- "%PYTHON%\\python.exe -m pytest"
