environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- "%PYTHON%\\python.exe -m pip install -r .requirements.txt"

test_script:
- "%PYTHON%\\python.exe -m pytest"
